"""empty message

Revision ID: 9c7719bcbe55
Revises: bceea86e0df1
Create Date: 2019-05-06 21:01:27.484697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c7719bcbe55'
down_revision = 'bceea86e0df1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excerpt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('score', sa.Column('excerpt_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'score', 'excerpt', ['excerpt_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'score', type_='foreignkey')
    op.drop_column('score', 'excerpt_id')
    op.drop_table('excerpt')
    # ### end Alembic commands ###
